// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNyJVaq-nS85Cxf0lnYXRx2wjl4q3yRY',
    appId: '1:128651604350:web:b3eca850ea923dcb00432f',
    messagingSenderId: '128651604350',
    projectId: 'crmdemo-8ff61',
    authDomain: 'crmdemo-8ff61.firebaseapp.com',
    storageBucket: 'crmdemo-8ff61.appspot.com',
    measurementId: 'G-JCMLJ635BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM-szhtg5q2GHNICe28i-rVK-LkzpdVhg',
    appId: '1:128651604350:android:8d7de1223fac55a400432f',
    messagingSenderId: '128651604350',
    projectId: 'crmdemo-8ff61',
    storageBucket: 'crmdemo-8ff61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWsi1SzRjgkwJn_rFjk1TUC06GlOD7Mgg',
    appId: '1:128651604350:ios:561326a8087e323b00432f',
    messagingSenderId: '128651604350',
    projectId: 'crmdemo-8ff61',
    storageBucket: 'crmdemo-8ff61.appspot.com',
    iosBundleId: 'com.rnw.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWsi1SzRjgkwJn_rFjk1TUC06GlOD7Mgg',
    appId: '1:128651604350:ios:2e04a32ea8ab798000432f',
    messagingSenderId: '128651604350',
    projectId: 'crmdemo-8ff61',
    storageBucket: 'crmdemo-8ff61.appspot.com',
    iosBundleId: 'com.rnw.crm.RunnerTests',
  );
}
