import 'package:carparking/PayRoll/model/payroll_model.dart';

import '../../../LeaveRequest/model/leave_model.dart';

class EmployeeModel {
  final String? employeeName;
  final String? employeeId;
  final String? employeeDept;
  final String? employeePunchIn;
  final String? employeePhoto;
  final String? team;
  final List<PayRollModel> payrollList;
  final List<LeaveModel> leaveList;

  EmployeeModel(
      {required this.employeeName,
      required this.employeeId,
      required this.employeePhoto,
      required this.payrollList,
      required this.team,
      required this.leaveList,
      required this.employeeDept,
      required this.employeePunchIn});
}

List<EmployeeModel> employeeList = [
  EmployeeModel(
      employeeName: 'Ashwanath',
      team: 'A Team',
      payrollList: [
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'June 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'May 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [
        LeaveModel(
            empId: 'Employee101',
            position: 'Senior Developer',
            requestDate: '21/03/2024',
            leaveType: 'Causal',
            reason: 'Personal Reason',
            totalDays: 2,
            fromDate: '22/03/2024',
            toDate: '23/03/2024',
            availableLeave: 10)
      ],
      employeeId: 'Employee101',
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmployeeModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee102',
      team: 'B Team',
      payrollList: [
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'June 2023'),
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmployeeModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee103',
      team: 'B Team',
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      payrollList: [
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmployeeModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee101',
      team: 'A Team',
      employeeDept: 'Developing',
      payrollList: [
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
];
