import 'package:carparking/PayRoll/model/payroll_model.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../LeaveRequest/model/leave_model.dart';

class EmpModel {
  final String? employeeName;
  final String? employeeId;
  final String? employeeDept;
  final String? employeePunchIn;
  final String? employeePhoto;
  final String? team;
  final List<PayRollModel> payrollList;
  final List<LeaveModel> leaveList;

  EmpModel(
      {required this.employeeName,
      required this.employeeId,
      required this.employeePhoto,
      required this.payrollList,
      required this.team,
      required this.leaveList,
      required this.employeeDept,
      required this.employeePunchIn});
}

class EmployeeModel {
  final String? employeeFirstName;
  final String? employeeImage;
  final String? employeeLastName;
  final String? employeeId;
  final String? docId;
  final String? employeeDept;
  final String? employeePunchIn;
  final String? team;
  final String? password;
  final String? employeeEmail;
  final String? employeePosition;
  final String? dob;
  final String? state;
  final String? city;
  final String? country;
  final String? gender;
  final String? status;
  final String? mobile;
  final String? home;
  final String? address;
  final String? issueDate;

  EmployeeModel({
    required this.city,
    required this.country,
    required this.gender,
    required this.status,
    required this.dob,
    required this.state,
    required this.mobile,
    required this.home,
    required this.address,
    required this.issueDate,
    required this.employeeFirstName,
    required this.employeeLastName,
    required this.employeeImage,
    required this.docId,
    required this.employeeId,
    required this.employeeDept,
    required this.employeePunchIn,
    required this.team,
    required this.password,
    required this.employeeEmail,
    required this.employeePosition,
  });

  factory EmployeeModel.fromFirebase(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    return EmployeeModel(
      employeeFirstName: doc.data()!['employeeFirstName'],
      employeeLastName: doc.data()!['employeeLastName'],
      employeeImage: doc.data()!['employeeImage'],
      employeeId: doc.data()!['employeeId'],
      employeeDept: doc.data()!['department'],
      employeePunchIn: doc.data()!['employeePunchIn'] ?? '',
      team: doc.data()!['team'],
      password: doc.data()!['password'],
      employeeEmail: doc.data()!['emailId'],
      employeePosition: doc.data()!['jobPosition'],
      docId: doc.id,
      dob: doc.data()!['dOB'],
      state: doc.data()!['state'],
      mobile: doc.data()!['mobileNumber'],
      home: doc.data()!['homeNumber'],
      address: doc.data()!['address'],
      issueDate: doc.data()!['issueDate'],
      city: doc.data()!['city'],
      country: doc.data()!['country'],
      gender:doc.data()!['gender'],
      status: doc.data()!['maritalStatus'],
    );
  }
}

List<EmpModel> employeeList = [
  EmpModel(
      employeeName: 'Ashwanath',
      team: 'A Team',
      payrollList: [
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'June 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'May 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [
        LeaveModel(
          empId: 'Employee101',
          position: 'Senior Developer',
          requestDate: '21/03/2024',
          leaveType: 'Causal',
          reason: 'Personal Reason',
          totalDays: '2',
          fromDate: '22/03/2024',
          toDate: '23/03/2024',
          status: 'Pending',
          empName: '',
          leaveId: '',
        )
      ],
      employeeId: 'Employee101',
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmpModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee102',
      team: 'B Team',
      payrollList: [
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'June 2023'),
        PayRollModel(
            id: 'Employee102',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmpModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee103',
      team: 'B Team',
      employeeDept: 'Developing',
      employeePunchIn: '8:04',
      payrollList: [
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee103',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
  EmpModel(
      employeeName: 'Ashwanath',
      employeeId: 'Employee101',
      team: 'A Team',
      employeeDept: 'Developing',
      payrollList: [
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'Employee101',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
        PayRollModel(
            id: 'HR1',
            jobStatus: 'Full Time',
            status: 'Pending',
            totalWorkDays: 26,
            workedDays: 25,
            additionalDays: 02,
            totalEarning: 55000,
            basicPayroll: 60000,
            dA: 500,
            otherPay: 500,
            totalDeduction: 22000,
            pf: 100,
            esi: 1000,
            month: 'July 2023'),
      ],
      leaveList: [],
      employeePunchIn: '8:04',
      employeePhoto:
          'https://img.freepik.com/premium-photo/business-woman-entrepreneur-working-office-professional-employee-workplace-young-beautiful-secretary-girl_265223-28262.jpg'),
];
